#CI项目
name: VIKINGYFY-Qihoo-360V6

on:
  workflow_dispatch:
  workflow_call:
  # schedule:
  #   - cron: 0 20 * * *

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: QihooV6
      #默认WIFI名称
      WRT_SSID: YM520
      #默认WIFI密码
      WRT_WORD: abc5124937,
      #默认地址
      WRT_IP: 192.168.2.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
